openapi: 3.0.0
info:
  title: Vonage Bulk API
  description: REST APIs for VCP Bulk Jobs & Lists
  version: 0.1.0
  contact:
    name: Nexmo.com
    email: devrel@nexmo.com
    url: "https://developer.nexmo.com/"
    x-twitter: Nexmo
  termsOfService: "https://www.nexmo.com/terms-of-use"
  license:
    name: The MIT License (MIT)
    url: "https://opensource.org/licenses/MIT"
  x-logo:
    url: "https://twitter.com/Nexmo/profile_image?size=original"
  x-apiClientRegistration: "https://dashboard.nexmo.com/sign-up"
  x-label: Alpha
tags:
  - name: actions
  - name: events
  - name: items
  - name: jobs
  - name: lists
  - name: runs
  - name: webhooks
servers:
  - url: https://api-eu.dev.v1.vonagenetworks.net/v0.1/bulk
    description: dev env in EU geo
  - url: https://api-eu.vonage.com/v0.1/bulk
    description: prod env in EU geo
security:
  - bearerAuth: [ ]
paths:
  /lists:
    get:
      operationId: findAllLists
      summary: Find all lists
      parameters:
        - example: 2
          required: false
          name: page
          in: query
          schema:
            minimum: 1
            default: 1
            type: number
        - name: page_size
          example: 100
          required: false
          in: query
          schema:
            minimum: 1
            maximum: 1000
            default: 100
            type: number
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/PageResponseDto'
                  - properties:
                      _embedded:
                        type: object
                        readOnly: true
                        properties:
                          lists:
                            type: array
                            readOnly: true
                            items:
                              $ref: '#/components/schemas/ListDto'
      tags:
        - lists
    post:
      operationId: createList
      summary: Create list
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateListDto'
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListDto'
      tags:
        - lists
  /lists/{list_id}:
    get:
      operationId: getList
      summary: Get list by id
      parameters:
        - name: list_id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListDto'
      tags:
        - lists
    put:
      operationId: updateList
      summary: Update list
      parameters:
        - name: list_id
          required: true
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateListDto'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListDto'
      tags:
        - lists
    delete:
      operationId: deleteList
      summary: Delete list
      parameters:
        - name: list_id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags:
        - lists
  /lists/{list_id}/reset:
    post:
      operationId: resetList
      summary: Reset list - delete all items
      parameters:
        - name: list_id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags:
        - lists
  /lists/{list_id}/refresh:
    post:
      operationId: refreshList
      summary: Refresh list - delete all items and sync from the datasource. Refresh is invalid for manual list
      parameters:
        - name: list_id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags:
        - lists
  /lists/{list_id}/items:
    get:
      operationId: listItems
      summary: Iterate over list items
      parameters:
        - name: list_id
          required: true
          in: path
          schema:
            type: string
        - example: 2
          required: false
          name: page
          in: query
          schema:
            minimum: 1
            default: 1
            type: number
        - name: page_size
          example: 100
          required: false
          in: query
          schema:
            minimum: 1
            maximum: 1000
            default: 100
            type: number
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/PageResponseDto'
                  - properties:
                      _embedded:
                        type: object
                        readOnly: true
                        properties:
                          items:
                            type: array
                            readOnly: true
                            items:
                              $ref: '#/components/schemas/ListItemDto'
      tags:
        - lists
        - items
    post:
      operationId: createListItem
      summary: Create list item
      parameters:
        - name: list_id
          required: true
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateListItemDto'
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListItemDto'
      tags:
        - lists
        - items
  /lists/{list_id}/items/download:
    get:
      operationId: downloadItems
      summary: Download list items
      parameters:
        - name: list_id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags:
        - lists
        - items
  /lists/{list_id}/items/{item_id}:
    get:
      operationId: getListItem
      summary: Get list item by id
      parameters:
        - name: list_id
          required: true
          in: path
          schema:
            type: string
        - name: item_id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListItemDto'
      tags:
        - lists
        - items
    put:
      operationId: updateListItem
      summary: Update list item
      parameters:
        - name: list_id
          required: true
          in: path
          schema:
            type: string
        - name: item_id
          required: true
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateListItemDto'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListItemDto'
      tags:
        - lists
        - items
    delete:
      operationId: deleteListItem
      summary: Delete list item
      parameters:
        - name: list_id
          required: true
          in: path
          schema:
            type: string
        - name: item_id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags:
        - lists
        - items
  /lists/{list_id}/items/import:
    post:
      operationId: importItems
      summary: Import list items
      parameters:
        - name: list_id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags:
        - lists
        - items
  /actions:
    get:
      operationId: findAllActions
      summary: Find all actions
      parameters:
        - example: 2
          required: false
          name: page
          in: query
          schema:
            minimum: 1
            default: 1
            type: number
        - name: page_size
          example: 100
          required: false
          in: query
          schema:
            minimum: 1
            maximum: 1000
            default: 100
            type: number
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/PageResponseDto'
                  - properties:
                      _embedded:
                        type: object
                        readOnly: true
                        properties:
                          actions:
                            type: array
                            readOnly: true
                            items:
                              $ref: '#/components/schemas/ActionDto'
      tags:
        - actions
    post:
      operationId: createAction
      summary: Create action_call
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateActionDto'
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActionDto'
      tags:
        - actions
  /actions/{id}:
    get:
      operationId: getAction
      summary: Get action by id
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActionDto'
      tags:
        - actions
    put:
      operationId: updateAction
      summary: Update action_call
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateActionDto'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActionDto'
      tags:
        - actions
    delete:
      operationId: deleteAction
      summary: Delete action_call
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActionDto'
      tags:
        - actions
  /jobs:
    get:
      operationId: findAllJobs
      summary: Find all jobs
      parameters:
        - example: 2
          required: false
          name: page
          in: query
          schema:
            minimum: 1
            default: 1
            type: number
        - name: page_size
          example: 100
          required: false
          in: query
          schema:
            minimum: 1
            maximum: 1000
            default: 100
            type: number
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/PageResponseDto'
                  - properties:
                      _embedded:
                        type: object
                        readOnly: true
                        properties:
                          jobs:
                            type: array
                            readOnly: true
                            items:
                              $ref: '#/components/schemas/JobDto'
      tags:
        - jobs
    post:
      operationId: createJob
      summary: Create job
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateJobDto'
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobDto'
      tags:
        - jobs
  /jobs/{id}:
    get:
      operationId: getJob
      summary: Get job by id
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobDto'
      tags:
        - jobs
    put:
      operationId: updateJob
      summary: Update job
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateJobDto'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobDto'
      tags:
        - jobs
    delete:
      operationId: deleteJob
      summary: Delete job
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags:
        - jobs
  /events:
    get:
      operationId: findEventsAll
      summary: Get events
      parameters:
        - example: 2
          required: false
          name: page
          in: query
          schema:
            minimum: 1
            default: 1
            type: number
        - name: page_size
          example: 100
          required: false
          in: query
          schema:
            minimum: 1
            maximum: 1000
            default: 100
            type: number
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/PageResponseDto'
                  - properties:
                      _embedded:
                        type: object
                        readOnly: true
                        properties:
                          events:
                            type: array
                            readOnly: true
                            items:
                              oneOf:
                                - $ref: '#/components/schemas/ActionCallSucceededEvent'
                                - $ref: '#/components/schemas/ActionCallFailedEvent'
                                - $ref: '#/components/schemas/ActionCallInfoEvent'
                                - $ref: '#/components/schemas/RecipientResponseEvent'
      tags:
        - events
  /runs:
    get:
      operationId: findAllRuns
      summary: Find all runs
      parameters:
        - example: 2
          required: false
          name: page
          in: query
          schema:
            minimum: 1
            default: 1
            type: number
        - name: page_size
          example: 100
          required: false
          in: query
          schema:
            minimum: 1
            maximum: 1000
            default: 100
            type: number
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/PageResponseDto'
                  - properties:
                      _embedded:
                        type: object
                        readOnly: true
                        properties:
                          runs:
                            type: array
                            readOnly: true
                            items:
                              $ref: '#/components/schemas/ActionDto'
      tags:
        - runs
    post:
      operationId: scheduleAtRun
      summary: Start job
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateJobRunDto'
      responses:
        '202':
          description: ''
      tags:
        - runs
  /runs/{id}:
    get:
      operationId: getJobRun
      summary: Get job run by id
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobRunDto'
      tags:
        - runs
  /runs/{id}/events:
    get:
      operationId: findEventsAllRun
      summary: Get job run events
      parameters:
        - example: 2
          required: false
          name: page
          in: query
          schema:
            minimum: 1
            default: 1
            type: number
        - name: page_size
          example: 100
          required: false
          in: query
          schema:
            minimum: 1
            maximum: 1000
            default: 100
            type: number
        - name: id
          required: true
          in: path
          schema: {}
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/PageResponseDto'
                  - properties:
                      _embedded:
                        type: object
                        readOnly: true
                        properties:
                          events:
                            type: array
                            readOnly: true
                            items:
                              oneOf:
                                - $ref: '#/components/schemas/ActionCallSucceededEvent'
                                - $ref: '#/components/schemas/ActionCallFailedEvent'
                                - $ref: '#/components/schemas/ActionCallInfoEvent'
                                - $ref: '#/components/schemas/RecipientResponseEvent'
      tags:
        - runs
  /runs/{id}/summary:
    get:
      operationId: getTotalStats
      summary: Get action runs and recipient responses statistics overview
      parameters:
        - name: id
          required: true
          in: path
          schema: {}
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatsRunSummaryDto'
      tags:
        - runs
  /runs/{id}/stop:
    post:
      operationId: stopJobRun
      summary: Initiate run stop
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '202':
          description: ''
      tags:
        - runs
  /webhooks/actions/status:
    post:
      operationId: actionStatus
      summary: Webhook endpoint to handle action call status for async actions
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - webhooks
      security:
        - {}
  /webhooks/recipients/responses:
    post:
      operationId: recipientResponse
      summary: Webhook endpoint to handle recipient responses
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - webhooks
      security:
        - {}
components:
  securitySchemes:
    bearerAuth:
      scheme: bearer
      bearerFormat: JWT
      type: http
  schemas:
    PageQueryDto:
      type: object
      properties:
        page:
          type: number
          minimum: 1
          default: 1
          example: 2
        page_size:
          type: number
          minimum: 1
          maximum: 1000
          default: 100
          example: 100
    Href:
      type: object
      properties:
        href:
          type: string
          format: url
          example: https://api-eu.vonage.com/v0.1/bulk/lists?page=5&page_size=10
      required:
        - href
    HalLinks:
      type: object
      properties:
        first:
          $ref: '#/components/schemas/Href'
        prev:
          $ref: '#/components/schemas/Href'
        self:
          $ref: '#/components/schemas/Href'
        next:
          $ref: '#/components/schemas/Href'
      required:
        - first
        - prev
        - self
        - next
    PageResponseDto:
      type: object
      properties:
        total_items:
          type: number
          readOnly: true
          example: 10000
        total_pages:
          type: number
          readOnly: true
          example: 50
        page:
          type: number
          readOnly: true
          minimum: 1
          example: 2
        page_size:
          type: number
          readOnly: true
          example: 250
        _links:
          readOnly: true
          type: array
          items:
            $ref: '#/components/schemas/HalLinks'
        _embedded:
          type: object
          additionalProperties: true
          readOnly: true
      required:
        - total_items
        - total_pages
        - page
        - page_size
        - _links
        - _embedded
    ListLabelDto:
      type: object
      properties:
        name:
          type: string
          maxLength: 50
          example: first_name
        alias:
          type: string
          maxLength: 50
        key:
          type: object
          default: false
      required:
        - name
    ListDto:
      type: object
      properties:
        id:
          type: string
          readOnly: true
          format: uuid
          example: 29192c4a-4058-49da-86c2-3e349d1065b7
        created_at:
          format: date-time
          type: string
          readOnly: true
          example: '2022-06-19T17:59:28.085Z'
        updated_at:
          format: date-time
          type: string
          readOnly: true
          example: '2022-06-19T17:59:28.085Z'
        name:
          type: string
          maxLength: 50
          example: Recipients for demo
        description:
          type: string
          maxLength: 1024
        tags:
          minItems: 0
          maxItems: 10
          type: array
          items:
            type: string
        labels:
          minItems: 0
          maxItems: 50
          type: array
          items:
            $ref: '#/components/schemas/ListLabelDto'
        items_count:
          type: number
          readOnly: true
          example: 10000
        datasource:
          discriminator:
            propertyName: type
          oneOf:
            - $ref: '#/components/schemas/SalesforceDatasource'
        sync_status:
          type: string
          readOnly: true
          enum:
            - configured
            - syncing
            - resetting
            - refreshing
            - paused
            - stopped
            - completed
            - failed
          example: configured
        type:
          type: string
          readOnly: true
          enum:
            - salesforce
            - manual
          example: salesforce
      required:
        - id
        - created_at
        - updated_at
        - name
        - items_count
        - sync_status
        - type
    CreateListDto:
      type: object
      properties:
        name:
          type: string
          maxLength: 50
          example: Recipients for demo
        description:
          type: string
          maxLength: 1024
        tags:
          minItems: 0
          maxItems: 10
          type: array
          items:
            type: string
        labels:
          minItems: 0
          maxItems: 50
          type: array
          items:
            $ref: '#/components/schemas/ListLabelDto'
        datasource:
          discriminator:
            propertyName: type
          oneOf:
            - $ref: '#/components/schemas/SalesforceDatasource'
        type:
          type: string
          readOnly: true
          enum:
            - salesforce
            - manual
          example: salesforce
      required:
        - name
        - type
    UpdateListDto:
      type: object
      properties:
        name:
          type: string
          maxLength: 50
          example: Recipients for demo
        description:
          type: string
          maxLength: 1024
        tags:
          minItems: 0
          maxItems: 10
          type: array
          items:
            type: string
        labels:
          minItems: 0
          maxItems: 50
          type: array
          items:
            $ref: '#/components/schemas/ListLabelDto'
        datasource:
          discriminator:
            propertyName: type
          oneOf:
            - $ref: '#/components/schemas/SalesforceDatasource'
        type:
          type: string
          readOnly: true
          enum:
            - salesforce
            - manual
          example: salesforce
    ListDatasourceBaseDto:
      type: object
      properties:
        type:
          type: string
          default: salesforce
          enum:
            - salesforce
          example: salesforce
      required:
        - type
    SalesforceDatasource:
      type: object
      properties:
        type:
          type: string
          default: salesforce
          enum:
            - salesforce
          example: salesforce
        integration_id:
          type: string
          example: salesforce_credentials
        soql:
          type: string
          example: select Id, LastName, FirstName, Phone, Email FROM Contact
      required:
        - type
        - integration_id
        - soql
    ListItemDto:
      type: object
      properties:
        id:
          type: string
          readOnly: true
          format: uuid
          example: 29192c4a-4058-49da-86c2-3e349d1065b7
        created_at:
          format: date-time
          type: string
          readOnly: true
          example: '2022-06-19T17:59:28.085Z'
        updated_at:
          format: date-time
          type: string
          readOnly: true
          example: '2022-06-19T17:59:28.085Z'
        list_id:
          type: string
          readOnly: true
          format: uuid
          example: 92cc64e5-f62b-464f-ab9c-4376bd05adfc
        data:
          type: object
          additionalProperties: true
          minProperties: 1
          maxProperties: 20
          example:
            firstName: Adrianna
            lastName: Renner
            number: 715-268-2905
      required:
        - id
        - created_at
        - updated_at
        - list_id
        - data
    ApiChangedDto:
      type: object
      properties:
        inserted:
          type: number
        updated:
          type: number
        deleted:
          type: number
    CreateListItemDto:
      type: object
      properties:
        data:
          type: object
          additionalProperties: true
          minProperties: 1
          maxProperties: 20
          example:
            firstName: Adrianna
            lastName: Renner
            number: 715-268-2905
      required:
        - data
    UpdateListItemDto:
      type: object
      properties:
        data:
          type: object
          additionalProperties: true
          minProperties: 1
          maxProperties: 20
          example:
            firstName: Adrianna
            lastName: Renner
            number: 715-268-2905
    ActionParameterDefinitionDto:
      type: object
      properties:
        type:
          type: string
          enum:
            - string
            - secret
          default: string
          example: string
        name:
          type: string
          example: from
        required:
          type: boolean
          default: true
          example: true
        default:
          type: string
      required:
        - type
        - name
        - required
    CreateActionDto:
      type: object
      properties:
        name:
          type: string
          example: send-sms
        parameters:
          type: array
          items:
            $ref: '#/components/schemas/ActionParameterDefinitionDto'
        command:
          discriminator:
            propertyName: type
          oneOf:
            - $ref: '#/components/schemas/HttpApiInvokeDto'
          example:
            type: http-api-invoke
            url: https://api.nexmo.com/v1/messages
            method: post
        timeout_seconds:
          type: number
          default: 5
          minimum: 0
          maximum: 60
      required:
        - name
        - command
    ActionParameterValueDto:
      type: object
      properties:
        name:
          type: string
          example: from_number
        value:
          type: string
          example: 715-268-2905
      required:
        - name
        - value
    ActionHttpResponseSuccessDto:
      type: object
      properties:
        codes:
          default:
            - '200'
          example:
            - 200
          type: array
          items:
            type: string
      required:
        - codes
    ActionHttpErrorDto:
      type: object
      properties:
        code:
          type: string
        details:
          type: string
          example: failed to run
      required:
        - details
    ActionHttpResponseDto:
      type: object
      properties:
        invocation_id:
          type: string
        success:
          $ref: '#/components/schemas/ActionHttpResponseSuccessDto'
        error:
          $ref: '#/components/schemas/ActionHttpErrorDto'
    ActionHttpAsyncStatusValuesDto:
      type: object
      properties:
        values:
          minItems: 1
          maxItems: 10
          example:
            - '202'
          type: array
          items:
            type: string
      required:
        - values
    ActionHttpAsyncErrorStatusDto:
      type: object
      properties:
        values:
          minItems: 1
          maxItems: 10
          example:
            - '202'
          type: array
          items:
            type: string
        details:
          type: string
          example: '{{ event.error.details }}'
      required:
        - values
        - details
    ActionHttpAsyncStatusDto:
      type: object
      properties:
        value:
          type: string
          example: '200'
        success:
          example: '200'
          allOf:
            - $ref: '#/components/schemas/ActionHttpAsyncStatusValuesDto'
        error:
          $ref: '#/components/schemas/ActionHttpAsyncErrorStatusDto'
        info:
          $ref: '#/components/schemas/ActionHttpAsyncStatusValuesDto'
      required:
        - value
        - success
    ActionHttpAsyncDto:
      type: object
      properties:
        invocation_id:
          type: string
          example: '{{ event.reqId }}'
        status:
          example:
            success:
              values:
                - ok
            error:
              values:
                - failed
              details: '{{ event.error.details }}'
            info:
              values:
                - submitted
            value: '{{ event.status }}'
          allOf:
            - $ref: '#/components/schemas/ActionHttpAsyncStatusDto'
      required:
        - invocation_id
        - status
    HttpApiInvokeDto:
      type: object
      properties:
        type:
          type: string
          default: http-api-invoke
          enum:
            - http-api-invoke
          example: http-api-invoke
        url:
          type: string
          example: https://api.nexmo.com/v1/messages
        method:
          type: string
          default: post
          example: post
        headers:
          type: array
          items:
            $ref: '#/components/schemas/ActionParameterValueDto'
        payload:
          type: object
        response:
          $ref: '#/components/schemas/ActionHttpResponseDto'
        async:
          $ref: '#/components/schemas/ActionHttpAsyncDto'
      required:
        - type
        - url
        - method
    ActionDto:
      type: object
      properties:
        id:
          type: string
          readOnly: true
          format: uuid
          example: 29192c4a-4058-49da-86c2-3e349d1065b7
        created_at:
          format: date-time
          type: string
          readOnly: true
          example: '2022-06-19T17:59:28.085Z'
        updated_at:
          format: date-time
          type: string
          readOnly: true
          example: '2022-06-19T17:59:28.085Z'
        name:
          type: string
          example: send-sms
        parameters:
          type: array
          items:
            $ref: '#/components/schemas/ActionParameterDefinitionDto'
        command:
          discriminator:
            propertyName: type
          oneOf:
            - $ref: '#/components/schemas/HttpApiInvokeDto'
          example:
            type: http-api-invoke
            url: https://api.nexmo.com/v1/messages
            method: post
        timeout_seconds:
          type: number
          default: 5
          minimum: 0
          maximum: 60
      required:
        - id
        - created_at
        - updated_at
        - name
        - command
    UpdateActionDto:
      type: object
      properties:
        name:
          type: string
          example: send-sms
        parameters:
          type: array
          items:
            $ref: '#/components/schemas/ActionParameterDefinitionDto'
        command:
          discriminator:
            propertyName: type
          oneOf:
            - $ref: '#/components/schemas/HttpApiInvokeDto'
          example:
            type: http-api-invoke
            url: https://api.nexmo.com/v1/messages
            method: post
        timeout_seconds:
          type: number
          default: 5
          minimum: 0
          maximum: 60
    ListRefDto:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: c4fd1c9e-80e7-4db1-94cb-8ec0edc154a4
        type:
          type: string
          enum:
            - list
          example: list
      required:
        - id
        - type
    RecipientsDto:
      type: object
      properties:
        include:
          minItems: 1
          maxItems: 10
          example:
            - type: list
              id: 42a5313b-ea90-4166-a950-00eb6f95dfef
          type: array
          items:
            $ref: '#/components/schemas/ListRefDto'
        exclude:
          minItems: 1
          maxItems: 10
          type: array
          items:
            $ref: '#/components/schemas/ListRefDto'
      required:
        - include
    ExpressionDto:
      type: object
      properties:
        expression:
          type: object
          maxLength: 256
          example: item.salary > 5000
      required:
        - expression
    ActionRefDto:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: c4fd1c9e-80e7-4db1-94cb-8ec0edc154a4
        type:
          type: string
          enum:
            - action
          example: action
      required:
        - id
        - type
    ActionCallDto:
      type: object
      properties:
        action_ref:
          example:
            type: action
            id: 20990a7c-db17-4e20-b485-ef9e1fd02f23
          allOf:
            - $ref: '#/components/schemas/ActionRefDto'
        parameters:
          maxItems: 20
          type: array
          items:
            $ref: '#/components/schemas/ActionParameterValueDto'
      required:
        - action_ref
    MessageTemplateDto:
      type: object
      properties:
        type:
          type: string
          default: text
        message:
          type: object
          maxLength: 8112
          default: ''
          example: Hello {{ item.firstName }} {{ item.lastName }}
        encoding:
          type: string
          default: utf8
          enum:
            - utf8
      required:
        - message
    RecipientCorrelationDto:
      type: object
      properties:
        correlation_id:
          type: string
          example: '{{event.from}}'
      required:
        - correlation_id
    SegmentationDto:
      type: object
      properties:
        condition:
          $ref: '#/components/schemas/ExpressionDto'
        action_call:
          $ref: '#/components/schemas/ActionCallDto'
        name:
          type: string
          maxLength: 255
        description:
          type: string
          maxLength: 1024
        template:
          $ref: '#/components/schemas/MessageTemplateDto'
        recipient:
          $ref: '#/components/schemas/RecipientCorrelationDto'
      required:
        - condition
        - action_call
        - recipient
    EventMatcherDto:
      type: object
      properties:
        condition:
          $ref: '#/components/schemas/ExpressionDto'
        action_call:
          $ref: '#/components/schemas/ActionCallDto'
        name:
          type: string
          maxLength: 255
        description:
          type: string
          maxLength: 1024
        recipient:
          $ref: '#/components/schemas/RecipientCorrelationDto'
      required:
        - condition
        - action_call
        - recipient
    EventsHandlerDto:
      type: object
      properties:
        matching_strategy:
          type: string
          default: match-first
          enum:
            - match-first
            - match-all
        matchers:
          type: array
          items:
            $ref: '#/components/schemas/EventMatcherDto'
      required:
        - matchers
    SegmentationJobDefinitionDto:
      type: object
      properties:
        type:
          type: string
          default: segmentation-job
          enum:
            - segmentation-job
          example: segmentation-job
        recipients:
          $ref: '#/components/schemas/RecipientsDto'
        segmentations:
          type: array
          items:
            $ref: '#/components/schemas/SegmentationDto'
        events_handler:
          $ref: '#/components/schemas/EventsHandlerDto'
      required:
        - type
        - recipients
        - segmentations
    JobDto:
      type: object
      properties:
        id:
          type: string
          readOnly: true
          format: uuid
          example: 29192c4a-4058-49da-86c2-3e349d1065b7
        created_at:
          format: date-time
          type: string
          readOnly: true
          example: '2022-06-19T17:59:28.085Z'
        updated_at:
          format: date-time
          type: string
          readOnly: true
          example: '2022-06-19T17:59:28.085Z'
        name:
          type: string
          example: Greeting all
        tags:
          minItems: 0
          maxItems: 30
          type: array
          items:
            type: string
        definition:
          discriminator:
            propertyName: type
          oneOf:
            - $ref: '#/components/schemas/SegmentationJobDefinitionDto'
          example:
            name: text vip customers
            description: text UK and USA vip customers
            recipient:
              correlation_id: '{{item.number}}'
            condition:
              expression: item.salary == 1000 || ['UK', 'USA'].includes(item.country)
            action_call:
              action_ref:
                id: '{{sendSmsActionId}}'
                type: action
              parameters:
                - name: fromNumber
                  value: '{{my_campaign_number}}'
                - name: toNumber
                  value: '{{ item.number }}'
                - name: message
                  value: '{{ template.message }}'
      required:
        - id
        - created_at
        - updated_at
        - name
        - definition
    CreateJobDto:
      type: object
      properties:
        name:
          type: string
          example: Greeting all
        tags:
          minItems: 0
          maxItems: 30
          type: array
          items:
            type: string
        definition:
          discriminator:
            propertyName: type
          oneOf:
            - $ref: '#/components/schemas/SegmentationJobDefinitionDto'
          example:
            name: text vip customers
            description: text UK and USA vip customers
            recipient:
              correlation_id: '{{item.number}}'
            condition:
              expression: item.salary == 1000 || ['UK', 'USA'].includes(item.country)
            action_call:
              action_ref:
                id: '{{sendSmsActionId}}'
                type: action
              parameters:
                - name: fromNumber
                  value: '{{my_campaign_number}}'
                - name: toNumber
                  value: '{{ item.number }}'
                - name: message
                  value: '{{ template.message }}'
      required:
        - name
        - definition
    UpdateJobDto:
      type: object
      properties:
        name:
          type: string
          example: Greeting all
        tags:
          minItems: 0
          maxItems: 30
          type: array
          items:
            type: string
        definition:
          discriminator:
            propertyName: type
          oneOf:
            - $ref: '#/components/schemas/SegmentationJobDefinitionDto'
          example:
            name: text vip customers
            description: text UK and USA vip customers
            recipient:
              correlation_id: '{{item.number}}'
            condition:
              expression: item.salary == 1000 || ['UK', 'USA'].includes(item.country)
            action_call:
              action_ref:
                id: '{{sendSmsActionId}}'
                type: action
              parameters:
                - name: fromNumber
                  value: '{{my_campaign_number}}'
                - name: toNumber
                  value: '{{ item.number }}'
                - name: message
                  value: '{{ template.message }}'
    ActionCallSucceededEvent:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: 92cc64e5-f62b-464f-ab9c-4376bd05adfc
        event_type:
          type: string
          enum:
            - action-call-succeeded
            - action-call-failed
            - action-call-info
            - recipient-response
            - run-item-skipped
            - run-item-failed
          example: action-call-succeeded
          readOnly: true
        src_ctx:
          type: string
          example: uk recipient
        occurred_at:
          format: date-time
          type: string
          example: '2022-06-19T20:41:59.085Z'
        event_data:
          type: object
          example:
            city: North Assunta
            country: Iceland
            state: PH
        job_id:
          type: string
          example: 1e46e0c5-709a-42ea-8e65-98b4bc604269
        job_run_id:
          type: string
          example: ce7b9294-0325-4a7a-b4c7-0b9ba531e27e
        recipient_id:
          type: object
          example: 29192c4a-4058-49da-86c2-3e349d1065b7
        action_id:
          type: string
          readOnly: true
          example: 125478b5-ef63-46e3-85d9-fdbee42c9242
        invocation_id:
          type: string
          example: 907cbc63-08de-4238-8fc9-8f9d67815d1b
      required:
        - id
        - event_type
        - src_ctx
        - occurred_at
        - event_data
        - job_id
        - job_run_id
        - recipient_id
        - action_id
    RecipientResponseEvent:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: 92cc64e5-f62b-464f-ab9c-4376bd05adfc
        event_type:
          type: string
          enum:
            - action-call-succeeded
            - action-call-failed
            - action-call-info
            - recipient-response
            - run-item-skipped
            - run-item-failed
          example: action-call-succeeded
        src_ctx:
          type: string
          example: uk recipient
        occurred_at:
          format: date-time
          type: string
          example: '2022-06-19T20:41:59.085Z'
        event_data:
          type: object
          example:
            city: North Assunta
            country: Iceland
            state: PH
        job_id:
          type: string
          example: 1e46e0c5-709a-42ea-8e65-98b4bc604269
        job_run_id:
          type: string
          example: ce7b9294-0325-4a7a-b4c7-0b9ba531e27e
        recipient_id:
          type: object
          example: 29192c4a-4058-49da-86c2-3e349d1065b7
      required:
        - id
        - event_type
        - src_ctx
        - occurred_at
        - event_data
        - job_id
        - job_run_id
        - recipient_id
    StatsMetricDto:
      type: object
      properties:
        name:
          type: string
          readOnly: true
          example: recipient-response
        statistics:
          type: string
          readOnly: true
          enum:
            - recipient-distinct-count
          example: recipient-distinct-count
        value:
          type: number
          readOnly: true
          example: 226
        occurred_at_min:
          format: date-time
          type: string
          readOnly: true
        occurred_at_max:
          format: date-time
          type: string
          readOnly: true
      required:
        - name
        - statistics
        - value
    ActionCallInfoEvent:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: 92cc64e5-f62b-464f-ab9c-4376bd05adfc
        event_type:
          type: string
          enum:
            - action-call-succeeded
            - action-call-failed
            - action-call-info
            - recipient-response
            - run-item-skipped
            - run-item-failed
          example: action-call-succeeded
          readOnly: true
        src_ctx:
          type: string
          example: uk recipient
        occurred_at:
          format: date-time
          type: string
          example: '2022-06-19T20:41:59.085Z'
        event_data:
          type: object
          example:
            city: North Assunta
            country: Iceland
            state: PH
        job_id:
          type: string
          example: 1e46e0c5-709a-42ea-8e65-98b4bc604269
        job_run_id:
          type: string
          example: ce7b9294-0325-4a7a-b4c7-0b9ba531e27e
        recipient_id:
          type: object
          example: 29192c4a-4058-49da-86c2-3e349d1065b7
        action_id:
          type: string
          readOnly: true
          example: a133c9e7-8cb8-4df9-a27f-b8e9065490da
        invocation_id:
          type: string
          example: a54c7944-ba11-45af-a146-3f0c9887d5f9
      required:
        - id
        - event_type
        - src_ctx
        - occurred_at
        - event_data
        - job_id
        - job_run_id
        - recipient_id
        - action_id
    EventErrorDto:
      type: object
      properties:
        code:
          type: string
        details:
          type: string
          example: Not found
      required:
        - details
    ActionCallFailedEvent:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: 92cc64e5-f62b-464f-ab9c-4376bd05adfc
        event_type:
          type: string
          enum:
            - action-call-succeeded
            - action-call-failed
            - action-call-info
            - recipient-response
            - run-item-skipped
            - run-item-failed
          example: action-call-failed
          readOnly: true
        src_ctx:
          type: string
          example: uk recipient
        occurred_at:
          format: date-time
          type: string
          example: '2022-06-19T20:41:59.085Z'
        event_data:
          type: object
          example:
            city: North Assunta
            country: Iceland
            state: PH
        job_id:
          type: string
          example: 1e46e0c5-709a-42ea-8e65-98b4bc604269
        job_run_id:
          type: string
          example: ce7b9294-0325-4a7a-b4c7-0b9ba531e27e
        recipient_id:
          type: object
          example: 29192c4a-4058-49da-86c2-3e349d1065b7
        action_id:
          type: string
          readOnly: true
          example: a133c9e7-8cb8-4df9-a27f-b8e9065490da
        invocation_id:
          type: string
          example: a54c7944-ba11-45af-a146-3f0c9887d5f9
        error:
          $ref: '#/components/schemas/EventErrorDto'
      required:
        - id
        - event_type
        - src_ctx
        - occurred_at
        - event_data
        - job_id
        - job_run_id
        - recipient_id
        - action_id
    CreateJobRunDto:
      type: object
      properties:
        name:
          type: string
          example: holiday run
        start_at:
          format: date-time
          type: string
          example: '2022-06-06T05:46:00.936Z'
        end_at:
          format: date-time
          type: string
          example: '2022-06-20T05:46:00.936Z'
        job_id:
          type: string
          format: uuid
          example: 06d5a6ed-cf02-4dbc-8694-164456f3f1c8
      required:
        - name
        - start_at
        - end_at
        - job_id
    JobRunDto:
      type: object
      properties:
        id:
          type: string
          readOnly: true
          format: uuid
          example: 29192c4a-4058-49da-86c2-3e349d1065b7
        created_at:
          format: date-time
          type: string
          readOnly: true
          example: '2022-06-19T17:59:28.085Z'
        updated_at:
          format: date-time
          type: string
          readOnly: true
          example: '2022-06-19T17:59:28.085Z'
        name:
          type: string
          example: holiday run
        start_at:
          format: date-time
          type: string
          example: '2022-06-06T05:46:00.936Z'
        end_at:
          format: date-time
          type: string
          example: '2022-06-20T05:46:00.936Z'
        job_id:
          type: string
          format: uuid
          example: 06d5a6ed-cf02-4dbc-8694-164456f3f1c8
        status:
          type: string
          readOnly: true
          enum:
            - scheduled
            - running
            - paused
            - stopped
            - failed
            - completed
            - draft
          example: running
      required:
        - id
        - created_at
        - updated_at
        - name
        - start_at
        - end_at
        - job_id
        - status
    StatsRunSummaryDto:
      type: object
      properties:
        job_run_id:
          type: string
          readOnly: true
          example: 42a5313b-ea90-4166-a950-00eb6f95dfef
        summary:
          readOnly: true
          example:
            - value: 3
              name: action-call-succeeded
              statistics: recipient-distinct-count
              occurred_at_min: '2022-06-20T05:52:49.063Z'
              occurred_at_max: '2022-06-20T05:52:49.099Z'
            - value: 0
              name: action-call-failed
              statistics: recipient-distinct-count
          type: array
          items:
            $ref: '#/components/schemas/StatsRunSummaryDto'
      required:
        - job_run_id
        - summary
